kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: custom-role-hello-world-namespace
  namespace: hello-world
rules:
- apiGroups: [""]
  resources: ["pods","secrets"]
  verbs: ["get", "list", "watch","create"]
